[package]
name = "wasmlette-blockchain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true
hex = "0.4"
bincode = "2.0.1"

[dev-dependencies]
rand.workspace = true
