[package]
name = "wasmlette-integration-tests"
version.workspace = true
edition.workspace = true

[dependencies]
wasmlette-blockchain = { path = "../crates/blockchain" }
wasmlette-runtime = { path = "../crates/runtime" }

[lib]
# This is not a library, just a test crate
path = "lib.rs"

# Disable running this as a regular test (we only want integration tests)
test = false

[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"
